export const en = {
  Name: "Name",
  Amount: "Amount",
  dimensions: "Dimensions",
  usage: "Usage",
  picture: "Picture",
  storage: "Storage Place",
  add: "Add new item",
  nameRequired: "Name is required",
  amountRequired: "Amount is required",
  amountMin: "Amount must be greater than 0",
  usageRequired: "Usage is required",
  edit: "Edit",
  generate: "Generate PDF",
};
