export const pl = {
  Name: "Nazwa artykułu",
  Amount: "Ilość sztuk",
  dimensions: "Wymiary",
  usage: "Zastosowanie",
  picture: "Zdjęcie",
  storage: "Miejsce przechowywania",
  add: "Dodaj nowe opakowanie",
  nameRequired: "Nazwa jest wymagana",
  amountRequired: "Ilość jest wymagana",
  amountMin: "Ilość musi być większa niż 0",
  usageRequired: "Zastosowanie jest wymagane",
  edit: "Edytuj",
  generate: "Generuj PDF",
};
